sudo: required
services:
  - docker:

before_install:
  - docker build -t boraozkan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run boraozkan/react-test npm test -- --coverage

after_success:
  - docker build -t boraozkan/multi-client ./client
  - docker build -t boraozkan/multi-nginx ./nginx
  - docker build -t boraozkan/multi-server ./server
  - docker build -t boraozkan/multi-worker ./worker
  #log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # take those images and push them to docker hub
  - docker push boraozkan/multi-client
  - docker push boraozkan/multi-nginx
  - docker push boraozkan/multi-server
  - docker push boraozkan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-312867154612
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY